export const ImageMap = {
  mouse: require("../assets/images/mouse.png"),
  phone: require("../assets/images/phone.png"),
  cardimage3: require("../assets/images/cardimage3.png"),
  smartwatch: require("../assets/images/smartwatch.png"),
  airpod: require("../assets/images/airpod.png"),
  phone2: require("../assets/images/phone2.png"),
  amazonecho: require("../assets/images/amazonecho.png"),
  Pixel3: require("../assets/images/Pixel3.png"),
  xiaomia2lute: require("../assets/images/xiaomia2lute.png"),
  iphonexr: require("../assets/images/iphonexr.png"),
  XIaomMiMix3: require("../assets/images/XIaomMiMix3.png"),
  order2: require("../assets/images/order2.png"),
  shoes: require("../assets/images/shoes.png"),
};
